In [5]:
import numpy as np

import torch

In [7]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(ft)
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
print(lt)
bt = torch.ByteTensor([[1, 2],
                       [3, 4]])
print(bt)
print(ft.dtype, lt.dtype, bt.dtype)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)
torch.float32 torch.int64 torch.uint8


In [4]:
x = torch.FloatTensor(3, 2)
print(x)
print(x.dtype)

tensor([[-9.5931e+21,  1.5400e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])
torch.float32


In [9]:
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x), x.dtype)
x = torch.from_numpy(x)
print(x, type(x), x.dtype)
x = x.numpy()
print(x, type(x), x.dtype)

[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'> torch.int64
[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64


In [10]:
print(ft.long(), ft.long().dtype)
print(lt.float(), lt.float().dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64
tensor([[1., 2.],
        [3., 4.]]) torch.float32


In [13]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.dtype, x.shape, x.dim())

torch.float32 torch.Size([3, 2, 2]) 3


In [17]:
# Why np array? There is no needs to do that.
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
print(a + b)
print(a == b)
print(a.mul(b))
print(a.sum(), a.mean())
print(a.sum(dim=0), a.sum(dim=-1))

tensor([[3., 4.],
        [6., 7.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor(10.) tensor(2.5000)
tensor([4., 6.]) tensor([3., 7.])


In [20]:
x = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
y = 1
print(x + y, (x + y).dtype)

tensor([[2., 3.],
        [4., 5.]]) torch.float32


In [24]:
x = torch.FloatTensor(np.array([[1, 2],
                                [4, 8]]))
y = torch.FloatTensor([3, 5])
z = torch.FloatTensor([3, 5]).reshape(-1, 1)
print(x.shape, y.shape, z.shape)
print(x + y, (x+y).dtype)
print(x + z, (x+z).dtype)

torch.Size([2, 2]) torch.Size([2]) torch.Size([2, 1])
tensor([[ 4.,  7.],
        [ 7., 13.]]) torch.float32
tensor([[ 4.,  5.],
        [ 9., 13.]]) torch.float32


In [27]:
x = torch.FloatTensor([[[1, 2], 
                        [3, 4]], 
                       [[5, 6], 
                        [7, 8]], 
                       [[9, 10], 
                        [11, 12]]])
print(x.shape)
print(x.reshape(3, 4))
print(x.reshape(2, -1, 3))

torch.Size([3, 2, 2])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [31]:
x = x.reshape(3, 4, 1)
print(x, x.shape)
x = x.squeeze()
print(x, x.shape)
x = x.unsqueeze(1)
print(x, x.shape)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]]) torch.Size([3, 4, 1])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) torch.Size([3, 4])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]]) torch.Size([3, 1, 4])
