In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([round((i+1)*0.1, 1) for i in range(9)]).reshape(3, -1)
print(target)
print(target.shape)
x = torch.rand_like(target)
x.requires_grad = True
print(x)
print(x.shape)

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])
torch.Size([3, 3])
tensor([[0.1825, 0.0786, 0.6948],
        [0.5197, 0.3393, 0.0305],
        [0.2565, 0.7717, 0.9946]], requires_grad=True)
torch.Size([3, 3])


In [3]:
mse_loss = nn.MSELoss()
loss = mse_loss(x, target)
print(loss)

tensor(0.0832, grad_fn=<MseLossBackward0>)


In [4]:
threshold = 1e-5
learning_rate = 0.1
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    if x.grad is not None:
        x.grad.zero_()

    loss.backward()

    with torch.no_grad():
        x = x - (learning_rate * x.grad)

    x.detach_()
    x.requires_grad_(True)

    loss = mse_loss(x, target)

    print(iter_cnt, loss)
    print(x)

1 tensor(0.0795, grad_fn=<MseLossBackward0>)
tensor([[0.1807, 0.0813, 0.6861],
        [0.5171, 0.3429, 0.0431],
        [0.2664, 0.7723, 0.9925]], requires_grad=True)
2 tensor(0.0760, grad_fn=<MseLossBackward0>)
tensor([[0.1789, 0.0839, 0.6775],
        [0.5145, 0.3464, 0.0555],
        [0.2760, 0.7729, 0.9904]], requires_grad=True)
3 tensor(0.0727, grad_fn=<MseLossBackward0>)
tensor([[0.1772, 0.0865, 0.6691],
        [0.5119, 0.3498, 0.0676],
        [0.2854, 0.7735, 0.9884]], requires_grad=True)
4 tensor(0.0695, grad_fn=<MseLossBackward0>)
tensor([[0.1754, 0.0890, 0.6609],
        [0.5095, 0.3531, 0.0794],
        [0.2947, 0.7741, 0.9864]], requires_grad=True)
5 tensor(0.0664, grad_fn=<MseLossBackward0>)
tensor([[0.1738, 0.0915, 0.6529],
        [0.5070, 0.3564, 0.0910],
        [0.3037, 0.7747, 0.9845]], requires_grad=True)
6 tensor(0.0635, grad_fn=<MseLossBackward0>)
tensor([[0.1721, 0.0939, 0.6450],
        [0.5046, 0.3596, 0.1023],
        [0.3125, 0.7753, 0.9826]], requires_gra