In [1]:
import numpy as np

import torch

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(ft)
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
print(lt)
bt = torch.ByteTensor([[1, 2],
                       [3, 4]])
print(bt)
print(ft.dtype, lt.dtype, bt.dtype)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)
torch.float32 torch.int64 torch.uint8


In [3]:
x = torch.FloatTensor(3, 2)
print(x)
print(x.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32


In [4]:
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x), x.dtype)
x = torch.from_numpy(x)
print(x, type(x), x.dtype)
x = x.numpy()
print(x, type(x), x.dtype)

[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'> torch.int64
[[1 2]
 [3 4]] <class 'numpy.ndarray'> int64


In [5]:
print(ft.long(), ft.long().dtype)
print(lt.float(), lt.float().dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64
tensor([[1., 2.],
        [3., 4.]]) torch.float32


In [6]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.dtype, x.shape, x.dim())

torch.float32 torch.Size([3, 2, 2]) 3


In [7]:
# Why np array? There is no needs to do that.
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
print(a + b)
print(a == b)
print(a.mul(b))
print(a.sum(), a.mean())
print(a.sum(dim=0), a.sum(dim=-1))

tensor([[3., 4.],
        [6., 7.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor(10.) tensor(2.5000)
tensor([4., 6.]) tensor([3., 7.])


In [8]:
x = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
y = 1
print(x + y, (x + y).dtype)

tensor([[2., 3.],
        [4., 5.]]) torch.float32


In [9]:
x = torch.FloatTensor(np.array([[1, 2],
                                [4, 8]]))
y = torch.FloatTensor([3, 5])
z = torch.FloatTensor([3, 5]).reshape(-1, 1)
print(x.shape, y.shape, z.shape)
print(x + y, (x+y).dtype)
print(x + z, (x+z).dtype)

torch.Size([2, 2]) torch.Size([2]) torch.Size([2, 1])
tensor([[ 4.,  7.],
        [ 7., 13.]]) torch.float32
tensor([[ 4.,  5.],
        [ 9., 13.]]) torch.float32


In [10]:
x = torch.FloatTensor([[[1, 2], 
                        [3, 4]], 
                       [[5, 6], 
                        [7, 8]], 
                       [[9, 10], 
                        [11, 12]]])
print(x.shape)
print(x.reshape(3, 4))
print(x.reshape(2, -1, 3))

torch.Size([3, 2, 2])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [11]:
x = x.reshape(3, 4, 1)
print(x, x.shape)
x = x.squeeze()
print(x, x.shape)
x = x.unsqueeze(1)
print(x, x.shape)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.],
         [12.]]]) torch.Size([3, 4, 1])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) torch.Size([3, 4])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]]) torch.Size([3, 1, 4])


In [19]:
x = torch.FloatTensor([[[1, 2], 
                        [3, 4]], 
                        [[5, 6], 
                         [7, 8]], 
                         [[9, 10], 
                          [11, 12]]])
print(x.shape)
print(x[0])
print(x[-1])
print(x[:, 0, :])
print(x[:, :, 0])
print(x[1:2, 1:, :])

torch.Size([3, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])
tensor([[[7., 8.]]])


In [22]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
for s in splits:
    print(s.shape)
print('----------------------')
chunks = x.chunk(4, dim=0)
for c in chunks:
    print(c.shape)

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])
----------------------
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


In [27]:
x = torch.FloatTensor([[[1, 2], 
                        [3, 4]], 
                        [[5, 6], 
                         [7, 8]], 
                         [[9, 10], 
                          [11, 12]]])
indice = torch.LongTensor([2, 1])
print(x.shape)
print(x.index_select(dim=0, index=indice))
print('---------------')
indice = torch.LongTensor([1])
print(x.index_select(dim=0, index=indice))

torch.Size([3, 2, 2])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])
---------------
tensor([[[5., 6.],
         [7., 8.]]])


In [36]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(x.shape, y.shape)
z = torch.concat([x, y], dim=0)
print(z)
print(z.shape)
print('---------------------')
z = torch.concat([x, y], dim=-1)
print(z)
print(z.shape)
print('---------------------')
z = torch.stack([x, y], dim=0)
print(z)
print(z.shape)
print('---------------------')
z = torch.stack([x, y], dim=1)
print(z)
print(z.shape)
print('---------------------')
z = torch.stack([x, y], dim=-1)
print(z)
print(z.shape)
print('---------------------')
d = 0
z = torch.concat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)
print(z)
print(z.shape)
print('---------------------')

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
---------------------
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])
---------------------
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
---------------------
tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]])
torch.Size([3, 2, 3])
---------------------
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
tor

In [39]:
x = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
x = x.unsqueeze(1)
print(x.shape)
print('-----------------')
y = x.expand(2, 3, 2)
print(y)
print(y.shape)

torch.Size([2, 1, 2])
-----------------
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [40]:
x = torch.randperm(10)
print(x)

tensor([1, 4, 5, 8, 3, 9, 2, 0, 6, 7])


In [44]:
x = torch.randperm(3**3).reshape(3, 3, -1)
print(x)
print(x.shape)
print('-----------------------')
y = x.argmax(dim=0)
print(y)
print(y.shape)
print('-----------------------')
y = x.argmax(dim=1)
print(y)
print(y.shape)
print('-----------------------')
y = x.argmax(dim=-1)
print(y)
print(y.shape)
print('-----------------------')

tensor([[[ 0, 12, 17],
         [25,  9,  3],
         [ 6, 20, 26]],

        [[ 2, 21, 19],
         [10,  5, 15],
         [ 8, 22,  1]],

        [[14, 13, 11],
         [16, 24, 23],
         [ 4,  7, 18]]])
torch.Size([3, 3, 3])
-----------------------
tensor([[2, 1, 1],
        [0, 2, 2],
        [1, 1, 0]])
torch.Size([3, 3])
-----------------------
tensor([[1, 2, 2],
        [1, 2, 0],
        [1, 1, 1]])
torch.Size([3, 3])
-----------------------
tensor([[2, 0, 2],
        [1, 2, 1],
        [0, 1, 2]])
torch.Size([3, 3])
-----------------------


In [49]:
x = torch.randperm(3**3).reshape(3, 3, -1)
print(x)
print(x.shape)
print('-----------------------')
values, indices = torch.topk(x, k=2, dim=0)
print(values.shape)
print(indices.shape)
print(indices)
print('-----------------------')

tensor([[[ 6,  5, 26],
         [ 0, 22, 20],
         [ 8, 18,  4]],

        [[13, 14, 21],
         [ 9, 25,  3],
         [10, 19, 23]],

        [[12, 16, 17],
         [11, 24, 15],
         [ 2,  7,  1]]])
torch.Size([3, 3, 3])
-----------------------
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])
tensor([[[1, 2, 0],
         [2, 1, 0],
         [1, 1, 1]],

        [[2, 1, 1],
         [1, 2, 2],
         [0, 0, 0]]])
-----------------------


In [50]:
print(torch.sort(x, dim=0, descending=True))

torch.return_types.sort(
values=tensor([[[13, 16, 26],
         [11, 25, 20],
         [10, 19, 23]],

        [[12, 14, 21],
         [ 9, 24, 15],
         [ 8, 18,  4]],

        [[ 6,  5, 17],
         [ 0, 22,  3],
         [ 2,  7,  1]]]),
indices=tensor([[[1, 2, 0],
         [2, 1, 0],
         [1, 1, 1]],

        [[2, 1, 1],
         [1, 2, 2],
         [0, 0, 0]],

        [[0, 0, 2],
         [0, 0, 1],
         [2, 2, 2]]]))


In [54]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)
print(x)
print(x.shape)
print('-----------------------')
mask = x > 4
print(mask)
print('-----------------------')
print(x.masked_fill(mask, value=-1))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])
-----------------------
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
-----------------------
tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [57]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))
print('-----------------------')
x = torch.randperm(6).reshape(1, 2, 3)
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
-----------------------
tensor([[[3, 4, 0],
         [5, 2, 1]]])
tensor([[[1, 1, 1],
         [1, 1, 1]]])
tensor([[[0, 0, 0],
         [0, 0, 0]]])
