In [1]:
import numpy as np

import torch
import torch.nn as nn

In [5]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([[1, 2]]).expand(2, 2)
print(x)
print(y)
print(x.shape, y.shape)
z = torch.matmul(x, y)
print(z)
print(z.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [1., 2.]])
torch.Size([3, 2]) torch.Size([2, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
torch.Size([3, 2])


In [6]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1).numpy()
y = torch.FloatTensor([[1, 2]]).expand(2, 2).numpy()
print(x)
print(y)
print(x.shape, y.shape)
z = np.dot(x, y)
print(z)
print(z.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1. 2.]
 [1. 2.]]
(3, 2) (2, 2)
[[ 3.  6.]
 [ 7. 14.]
 [11. 22.]]
(3, 2)


In [7]:
x = torch.FloatTensor(3, 3, 2)
y = torch.FloatTensor(3, 2, 3)
z = torch.bmm(x, y)
print(z)
print(z.shape)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([3, 3, 3])


In [12]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=4, output_dim=3):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [15]:
linear = MyLinear(3, 2)
x = torch.FloatTensor(4, 3)
y = linear(x)
print(y)

tensor([[0.0000, 4.4766],
        [0.0000, 4.4766],
        [0.0000, 4.4766],
        [0.0000, 4.4766]], grad_fn=<AddBackward0>)


In [16]:
linear = nn.Linear(3, 2)
x = torch.FloatTensor(4, 3)
y = linear(x)
print(y)
for p in linear.parameters():
    print(p)

tensor([[0.1006, 0.1599],
        [0.1006, 0.1599],
        [0.1006, 0.1599],
        [0.1006, 0.1599]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.3468, -0.4788, -0.1367],
        [-0.1888, -0.3892,  0.4286]], requires_grad=True)
Parameter containing:
tensor([0.1006, 0.1599], requires_grad=True)


In [19]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)

cuda


In [20]:
x = torch.FloatTensor(2, 2)
print(x)
x = x.to(device)
print(x)

tensor([[-5.2846e+20,  2.1877e+00],
        [ 0.0000e+00,  0.0000e+00]])
tensor([[-5.2846e+20,  2.1877e+00],
        [ 0.0000e+00,  0.0000e+00]], device='cuda:0')


In [22]:
layer = nn.Linear(2, 2).to(device)
next(layer.parameters()).device

device(type='cuda', index=0)

In [23]:
del layer
del x
torch.cuda.empty_cache()