In [6]:
import torch
import numpy as np

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 6.7262e-44]])

In [7]:
x = np.array([[1, 2],
              [3, 4]])
x = torch.from_numpy(x)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.size(), x.shape, x.dim()

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]), 3)

In [10]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
a + b

tensor([[3., 4.],
        [6., 7.]])

In [11]:
a.sum(), a.mean(), a.sum(dim=0), a.sum(dim=-1)

(tensor(10.), tensor(2.5000), tensor([4., 6.]), tensor([3., 7.]))

In [13]:
torch.from_numpy(np.dot(a, b))

tensor([[ 8.,  8.],
        [18., 18.]])

In [14]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [20]:
y = x.reshape(-1, 1, 4)
y, y.shape

(tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]),
 torch.Size([3, 1, 4]))

In [19]:
y.squeeze(), y.squeeze().shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [21]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [27]:
x[0], x[-1], x[:, 0], x[1:, 1:, :]

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[ 9., 10.],
         [11., 12.]]),
 tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[[ 7.,  8.]],
 
         [[11., 12.]]]))

In [28]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [29]:
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [31]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
indice = torch.LongTensor([2, 1])
x.shape

torch.Size([3, 2, 2])

In [35]:
y = x.index_select(dim=0, index=indice)
y, y.shape

(tensor([[[ 9., 10.],
          [11., 12.]],
 
         [[ 5.,  6.],
          [ 7.,  8.]]]),
 torch.Size([2, 2, 2]))

In [36]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [38]:
torch.concat([x, y], dim=0), torch.concat([x, y], dim=-1)

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]),
 tensor([[ 1.,  2.,  3., 10., 11., 12.],
         [ 4.,  5.,  6., 13., 14., 15.],
         [ 7.,  8.,  9., 16., 17., 18.]]))

In [40]:
torch.stack([x, y], dim=0), torch.stack([x, y], dim=-1)

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1., 10.],
          [ 2., 11.],
          [ 3., 12.]],
 
         [[ 4., 13.],
          [ 5., 14.],
          [ 6., 15.]],
 
         [[ 7., 16.],
          [ 8., 17.],
          [ 9., 18.]]]))