In [6]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [3]:
torch.matmul(x, y)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [4]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[15,  1],
          [ 8, 11],
          [ 9,  5]],
 
         [[12, 16],
          [ 6, 14],
          [10, 13]],
 
         [[ 4,  2],
          [ 0, 17],
          [ 7,  3]]]),
 tensor([[[ 1, 15, 10],
          [ 7, 13,  4]],
 
         [[ 6, 12, 17],
          [11,  5, 16]],
 
         [[ 8,  2,  3],
          [ 9,  0, 14]]]))

In [5]:
torch.bmm(x, y)

tensor([[[ 22, 238, 154],
         [ 85, 263, 124],
         [ 44, 200, 110]],

        [[248, 224, 460],
         [190, 142, 326],
         [203, 185, 378]],

        [[ 50,   8,  40],
         [153,   0, 238],
         [ 83,  14,  63]]])

In [7]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=3):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
    
    def forward(self, X):
        y = torch.matmul(x, self.W) + self.b
        return y

In [9]:
linear = MyLinear(3, 2)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[6.3058e-44, 6.7262e-44],
        [7.4269e-44, 6.3058e-44],
        [7.0065e-44, 6.8664e-44]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [11]:
linear = nn.Linear(3, 2)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.2834, -0.4318,  0.1703],
        [-0.0953,  0.4289, -0.3803]], requires_grad=True)
Parameter containing:
tensor([-0.5375, -0.5434], requires_grad=True)


In [12]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=3):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, X):
        y = self.Linear(X)
        return y

In [13]:
linear = MyLinear(3, 2)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.0344, -0.3845,  0.0636],
        [ 0.5550, -0.0420,  0.4278]], requires_grad=True)
Parameter containing:
tensor([-0.0455, -0.1088], requires_grad=True)
