In [1]:
import torch
import numpy as np

In [2]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [3]:
torch.matmul(x, y)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [4]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[15,  1],
          [ 8, 11],
          [ 9,  5]],
 
         [[12, 16],
          [ 6, 14],
          [10, 13]],
 
         [[ 4,  2],
          [ 0, 17],
          [ 7,  3]]]),
 tensor([[[ 1, 15, 10],
          [ 7, 13,  4]],
 
         [[ 6, 12, 17],
          [11,  5, 16]],
 
         [[ 8,  2,  3],
          [ 9,  0, 14]]]))

In [5]:
torch.bmm(x, y)

tensor([[[ 22, 238, 154],
         [ 85, 263, 124],
         [ 44, 200, 110]],

        [[248, 224, 460],
         [190, 142, 326],
         [203, 185, 378]],

        [[ 50,   8,  40],
         [153,   0, 238],
         [ 83,  14,  63]]])