In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
target = torch.FloatTensor([i * 0.1 + 0.1 for i in range(9)]).reshape(3, 3)
target

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [3]:
X = torch.rand_like(target)
X.requires_grad = True

In [4]:
X

tensor([[0.8326, 0.4895, 0.7254],
        [0.4519, 0.9958, 0.5701],
        [0.2889, 0.0670, 0.3210]], requires_grad=True)

In [6]:
loss = F.mse_loss(X, target)
loss

tensor(0.2325, grad_fn=<MseLossBackward0>)

In [8]:
thres = 1e-5
lr = 0.1
iter_cnt = 0

In [9]:
while loss > thres:
    iter_cnt += 1
    loss.backward()
    X = X - lr * X.grad
    X.detach_()
    X.requires_grad_(True)
    loss = F.mse_loss(X, target)
    print(X)
    print(loss)

tensor([[0.8163, 0.4830, 0.7159],
        [0.4508, 0.9847, 0.5707],
        [0.2980, 0.0833, 0.3338]], requires_grad=True)
tensor(0.2223, grad_fn=<MseLossBackward0>)
tensor([[0.8004, 0.4767, 0.7067],
        [0.4496, 0.9740, 0.5714],
        [0.3069, 0.0992, 0.3464]], requires_grad=True)
tensor(0.2125, grad_fn=<MseLossBackward0>)
tensor([[0.7848, 0.4706, 0.6977],
        [0.4485, 0.9634, 0.5720],
        [0.3157, 0.1148, 0.3587]], requires_grad=True)
tensor(0.2032, grad_fn=<MseLossBackward0>)
tensor([[0.7696, 0.4646, 0.6888],
        [0.4475, 0.9531, 0.5726],
        [0.3242, 0.1300, 0.3707]], requires_grad=True)
tensor(0.1942, grad_fn=<MseLossBackward0>)
tensor([[0.7547, 0.4587, 0.6802],
        [0.4464, 0.9431, 0.5732],
        [0.3326, 0.1449, 0.3825]], requires_grad=True)
tensor(0.1857, grad_fn=<MseLossBackward0>)
tensor([[0.7402, 0.4529, 0.6717],
        [0.4454, 0.9332, 0.5738],
        [0.3407, 0.1594, 0.3940]], requires_grad=True)
tensor(0.1775, grad_fn=<MseLossBackward0>)
tens