In [1]:
import torch
import numpy as np

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 6.4320e-43],
        [1.8754e+28, 1.0153e-08],
        [1.0256e-08, 1.0481e-11]])

In [4]:
x = np.array([[1, 2],
              [3, 4]])
x = torch.from_numpy(x)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.size(), x.shape, x.dim()

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]), 3)

In [6]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
a + b

tensor([[3., 4.],
        [6., 7.]])

In [7]:
a.sum(), a.mean(), a.sum(dim=0), a.sum(dim=-1)

(tensor(10.), tensor(2.5000), tensor([4., 6.]), tensor([3., 7.]))

In [8]:
torch.from_numpy(np.dot(a, b))

tensor([[ 8.,  8.],
        [18., 18.]])

In [9]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [10]:
y = x.reshape(-1, 1, 4)
y, y.shape

(tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]),
 torch.Size([3, 1, 4]))

In [11]:
y.squeeze(), y.squeeze().shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [12]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [13]:
x[0], x[-1], x[:, 0], x[1:, 1:, :]

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[ 9., 10.],
         [11., 12.]]),
 tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[[ 7.,  8.]],
 
         [[11., 12.]]]))

In [14]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [15]:
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [16]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
indice = torch.LongTensor([2, 1])
x.shape

torch.Size([3, 2, 2])

In [17]:
y = x.index_select(dim=0, index=indice)
y, y.shape

(tensor([[[ 9., 10.],
          [11., 12.]],
 
         [[ 5.,  6.],
          [ 7.,  8.]]]),
 torch.Size([2, 2, 2]))

In [18]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [19]:
torch.concat([x, y], dim=0), torch.concat([x, y], dim=-1)

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]),
 tensor([[ 1.,  2.,  3., 10., 11., 12.],
         [ 4.,  5.,  6., 13., 14., 15.],
         [ 7.,  8.,  9., 16., 17., 18.]]))

In [20]:
torch.stack([x, y], dim=0), torch.stack([x, y], dim=-1)

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1., 10.],
          [ 2., 11.],
          [ 3., 12.]],
 
         [[ 4., 13.],
          [ 5., 14.],
          [ 6., 15.]],
 
         [[ 7., 16.],
          [ 8., 17.],
          [ 9., 18.]]]))

In [24]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
a.reshape(2, 1, 2).expand(2, 3, 2)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [25]:
torch.randperm(10)

tensor([6, 1, 3, 5, 4, 2, 8, 0, 9, 7])

In [26]:
x = torch.randperm(3 ** 3).reshape(3, 3, -1)
x

tensor([[[22, 16,  3],
         [ 0, 17, 26],
         [ 5, 20, 21]],

        [[ 7, 14, 19],
         [11,  1, 25],
         [18, 23,  9]],

        [[ 6,  2,  4],
         [13, 12,  8],
         [15, 24, 10]]])

In [32]:
x.argmax(dim=0), x.argmax(dim=1), x.argmax(dim=2)

(tensor([[0, 0, 1],
         [2, 0, 0],
         [1, 2, 0]]),
 tensor([[0, 2, 1],
         [2, 2, 1],
         [2, 2, 2]]),
 tensor([[0, 2, 2],
         [2, 2, 1],
         [0, 0, 1]]))

In [33]:
torch.topk(x, k=1, dim=1)

torch.return_types.topk(
values=tensor([[[22, 20, 26]],

        [[18, 23, 25]],

        [[15, 24, 10]]]),
indices=tensor([[[0, 2, 1]],

        [[2, 2, 1]],

        [[2, 2, 2]]]))

In [34]:
torch.sort(x, dim=1, descending=True)

torch.return_types.sort(
values=tensor([[[22, 20, 26],
         [ 5, 17, 21],
         [ 0, 16,  3]],

        [[18, 23, 25],
         [11, 14, 19],
         [ 7,  1,  9]],

        [[15, 24, 10],
         [13, 12,  8],
         [ 6,  2,  4]]]),
indices=tensor([[[0, 2, 1],
         [2, 1, 2],
         [1, 0, 0]],

        [[2, 2, 1],
         [1, 0, 0],
         [0, 1, 2]],

        [[2, 2, 2],
         [1, 1, 1],
         [0, 0, 0]]]))

In [36]:
x = torch.FloatTensor([i for i in range(3 ** 2)]).reshape(3, -1)
mask = x > 4

In [38]:
y = x.masked_fill(mask, value=-1)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])